### ISSUE TITLE
[Jenkins CI]  cannot create image.openshift.io.imagestreamimports

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-qe#125] opened 2017-10-19 13:05 UTC
```
Using the ‘stage’ step without a block argument is deprecated
Entering stage Prepare test environment
Proceeding
[Pipeline] createEnvironment
[INFO] 18 10 2017 - 13:24: Executing environment setup script from:https://raw.githubusercontent.com/syndesisio/syndesis-system-tests/master/src/test/resources/setup.sh
[INFO] 18 10 2017 - 13:24: Installing Syndesis in syndesis-e2e-tests from: https://raw.githubusercontent.com/syndesisio/syndesis-openshift-templates/master/syndesis-ci.yml
[INFO] 18 10 2017 - 13:24: Now using project "syndesis-e2e-tests" on server "https://172.30.0.1:443".
[INFO] 18 10 2017 - 13:24: ImageStreams specified by template will be used
[INFO] 18 10 2017 - 13:24: template "syndesis-ci" created
[ERROR] 18 10 2017 - 13:24: error: Errors occurred while determining argument types:
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24: syndesis-ci as a local directory pointing to a Git repository:  stat syndesis-ci: no such file or directory
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24: Errors occurred during resource creation:
[ERROR] 18 10 2017 - 13:24: error: can't lookup images: User "system:serviceaccount:syndesis-ci:jenkins" cannot create image.openshift.io.imagestreamimports in project "syndesis-e2e-tests"
[ERROR] 18 10 2017 - 13:24: error: no match for "syndesis-ci"
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24: The 'oc new-app' command will match arguments to the following types:
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24:   1. Images tagged into image streams in the current project or the 'openshift' project
[ERROR] 18 10 2017 - 13:24:      - if you don't specify a tag, we'll add ':latest'
[ERROR] 18 10 2017 - 13:24:   2. Images in the Docker Hub, on remote registries, or on the local Docker engine
[ERROR] 18 10 2017 - 13:24:   3. Templates in the current project or the 'openshift' project
[ERROR] 18 10 2017 - 13:24:   4. Git repository URLs or local paths that point to Git repositories
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24: --allow-missing-images can be used to point to an image that does not exist yet.
[ERROR] 18 10 2017 - 13:24: 
[ERROR] 18 10 2017 - 13:24: See 'oc new-app -h' for examples.
[WARNING] 18 10 2017 - 13:24: Did not find any kubernetes configuration.
[Pipeline] podTemplate
[Pipeline] {
```

**Comment by mmelko** [comment] 2017-10-19 13:08
@iocanel FYI,
do you have any news about this ?

**Comment by iocanel** [comment] 2017-10-19 13:34
I am afraid not.

**Comment by dsimansk** [comment] 2017-10-24 06:17
@iocanel I've tried to run tests today and it's working as before. Did you manage to find out the root cause?

**Comment by iocanel** [comment] 2017-10-24 06:20
@dsimansk: Yes, the latest jenkins image we picked from openshift is using 3.7 version of the oc binaries which seem to be why this is not working.

**Comment by dsimansk** [comment] 2017-10-24 06:23
@iocanel thanks a lot. I'll close this issue then.

**Closed by dsimansk** 2017-10-24 06:23 UTC
Labels: automation, help wanted
